### ISSUE TITLE
Final Capstone Kanban board 

### ISSUE THREAD

**Issue by IamYunusAli** [IamYunusAli/Eventify-backend#16]
We are a team of 4 developers
@IamYunusAli @fullstop125 @29td  and @betses 

[Kanban board](https://github.com/users/IamYunusAli/projects/3/views/1) 

![kanbard](https://user-images.githubusercontent.com/32224137/210531113-c0fe92aa-c9a4-40d8-a5a0-69a17a0c74c3.png)

[Frontend](https://github.com/betses/Final-capstone--frontend
)

**Comment by Meltrust** [comment]
Hi @IamYunusAli,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not contain a screenshot of the kanban board.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Meltrust** [comment]
Hi @IamYunusAli,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- All cards have been assigned, and pointed✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

According to the project requirements:

![image](https://user-images.githubusercontent.com/57421823/210532096-e60e4e30-0343-44eb-bd1e-e631390c00fe.png)

Therefore:

- [ ] Kindly add descriptions to the cards that are missing one (I counted 9 cards without a description).  The descriptions don't have to be too complicated or long, just clear.  I hope this helps.

- [ ] Also, this is the spread of the work in points:

16 points: fullstop125
16 points: betses
12 points: 29td
11 points: iamyunusali

Kindly, ensure the points difference among members is never equal or greater than 5 points.  Thus, 29td and iamyunusali should have a number of points more equal than betses and fullstop25.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Meltrust** [comment]
Hi STUDENT_MENTION,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- The paintings are feared now and all tasks have descriptions. Good work.✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
